#include <stdio.h>
int main(){
	printf(" NAME_OF_THE_PERSON_=_SARMISHTA\n AGE_=_18\n DATE_OF_BIRTH_=_08/07/2004\n BLOOD_GROUP_=_-O_VE\n FATHER_NAME_=_YADAGIRI\n 
			MOTHER_NAME_=_REKHA\n ADDRESS_=_101,2nd_FLOOR_DIAMOND_PALACE_EENADU_COLONY_KUKATPALL,_HYDERABAD\n
			PHONE_NUMBER_=_9100557508\n PLACE_OF_BIRTH_=_GUNTUR\n");
}
